//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.24 at 10:45:17 PM MSK 
//


package com.sevtrans.monitor.dto;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Заказ на поставку/отгрузку
 *
 * <p>Java class for Order complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Order">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="orderNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="orderDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="plannedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="orderType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Поставка"/>
 *               &lt;enumeration value="Отгрузка"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="deliveryType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contractor" type="{http://www.sevtrans.com}Contractor" minOccurs="0"/>
 *         &lt;element name="vehicle" type="{http://www.sevtrans.com}Vehicle" minOccurs="0"/>
 *         &lt;element name="lineItem" type="{http://www.sevtrans.com}OrderLineItem" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Order", propOrder = {
        "orderNo",
        "orderDate",
        "plannedDate",
        "orderType",
        "deliveryType",
        "contractor",
        "vehicle",
        "lineItem"
})
@XmlSeeAlso({
        DeliveryOrder.class,
        ShipmentOrder.class
})
public class Order {

    @XmlElement(required = true)
    protected String orderNo;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1.class)
    @XmlSchemaType(name = "dateTime")
    protected Calendar orderDate;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1.class)
    @XmlSchemaType(name = "dateTime")
    protected Calendar plannedDate;
    @XmlElement(required = true)
    protected String orderType;
    @XmlElement(required = true)
    protected String deliveryType;
    protected Contractor contractor;
    protected Vehicle vehicle;
    @XmlElement(required = true)
    protected List<OrderLineItem> lineItem;

    /**
     * Gets the value of the orderNo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * Sets the value of the orderNo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOrderNo(String value) {
        this.orderNo = value;
    }

    /**
     * Gets the value of the orderDate property.
     *
     * @return possible object is
     * {@link String }
     */
    public Calendar getOrderDate() {
        return orderDate;
    }

    /**
     * Sets the value of the orderDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOrderDate(Calendar value) {
        this.orderDate = value;
    }

    /**
     * Gets the value of the plannedDate property.
     *
     * @return possible object is
     * {@link String }
     */
    public Calendar getPlannedDate() {
        return plannedDate;
    }

    /**
     * Sets the value of the plannedDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPlannedDate(Calendar value) {
        this.plannedDate = value;
    }

    /**
     * Gets the value of the orderType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * Sets the value of the orderType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOrderType(String value) {
        this.orderType = value;
    }

    /**
     * Gets the value of the deliveryType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDeliveryType() {
        return deliveryType;
    }

    /**
     * Sets the value of the deliveryType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDeliveryType(String value) {
        this.deliveryType = value;
    }

    /**
     * Gets the value of the contractor property.
     *
     * @return possible object is
     * {@link Contractor }
     */
    public Contractor getContractor() {
        return contractor;
    }

    /**
     * Sets the value of the contractor property.
     *
     * @param value allowed object is
     *              {@link Contractor }
     */
    public void setContractor(Contractor value) {
        this.contractor = value;
    }

    /**
     * Gets the value of the vehicle property.
     *
     * @return possible object is
     * {@link Vehicle }
     */
    public Vehicle getVehicle() {
        return vehicle;
    }

    /**
     * Sets the value of the vehicle property.
     *
     * @param value allowed object is
     *              {@link Vehicle }
     */
    public void setVehicle(Vehicle value) {
        this.vehicle = value;
    }

    /**
     * Gets the value of the lineItem property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lineItem property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLineItem().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderLineItem }
     */
    public List<OrderLineItem> getLineItem() {
        if (lineItem == null) {
            lineItem = new ArrayList<OrderLineItem>();
        }
        return this.lineItem;
    }

}
