//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.06 at 12:45:52 PM MSK 
//


package com.sevtrans.monitor.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="msgType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="customerID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="customer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;choice>
 *           &lt;element name="product" type="{http://www.sevtrans.com}Product"/>
 *           &lt;element name="order" type="{http://www.sevtrans.com}Order"/>
 *           &lt;element name="deliveryOrder" type="{http://www.sevtrans.com}DeliveryOrder"/>
 *           &lt;element name="shipmentOrder" type="{http://www.sevtrans.com}ShipmentOrder"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "msgType",
    "customerID",
    "customer",
    "product",
    "order",
    "deliveryOrder",
    "shipmentOrder"
})
@XmlRootElement(name = "Shell")
public class Shell {

    @XmlElement(required = true)
    protected String msgType;
    protected int customerID;
    @XmlElement(required = true)
    protected String customer;
    protected Product product;
    protected Order order;
    protected DeliveryOrder deliveryOrder;
    protected ShipmentOrder shipmentOrder;

    /**
     * Gets the value of the msgType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgType() {
        return msgType;
    }

    /**
     * Sets the value of the msgType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgType(String value) {
        this.msgType = value;
    }

    /**
     * Gets the value of the customerID property.
     * 
     */
    public int getCustomerID() {
        return customerID;
    }

    /**
     * Sets the value of the customerID property.
     * 
     */
    public void setCustomerID(int value) {
        this.customerID = value;
    }

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomer(String value) {
        this.customer = value;
    }

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link Product }
     *     
     */
    public Product getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link Product }
     *     
     */
    public void setProduct(Product value) {
        this.product = value;
    }

    /**
     * Gets the value of the order property.
     * 
     * @return
     *     possible object is
     *     {@link Order }
     *     
     */
    public Order getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link Order }
     *     
     */
    public void setOrder(Order value) {
        this.order = value;
    }

    /**
     * Gets the value of the deliveryOrder property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryOrder }
     *     
     */
    public DeliveryOrder getDeliveryOrder() {
        return deliveryOrder;
    }

    /**
     * Sets the value of the deliveryOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryOrder }
     *     
     */
    public void setDeliveryOrder(DeliveryOrder value) {
        this.deliveryOrder = value;
    }

    /**
     * Gets the value of the shipmentOrder property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentOrder }
     *     
     */
    public ShipmentOrder getShipmentOrder() {
        return shipmentOrder;
    }

    /**
     * Sets the value of the shipmentOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentOrder }
     *     
     */
    public void setShipmentOrder(ShipmentOrder value) {
        this.shipmentOrder = value;
    }

}
