create table KB_SOST
(
    id                     VARCHAR(38)            not null,
    fk_id                  VARCHAR(38),
    id_obsl                VARCHAR(38),
    id_sost                VARCHAR(38),
    id_tir                 VARCHAR(38),
    id_gtd                 VARCHAR(38),
    id_isp                 VARCHAR(38),
    id_du                  VARCHAR(38),
    id_ttn                 VARCHAR(38),
    dt_sost                TIMESTAMP(0) default NOW(),
    dt_sost_end            TIMESTAMP(0),
    sost_doc               VARCHAR(100),
    sost_prm               VARCHAR(4000),
    cnt_usl                NUMERIC(16, 4),
    kpogr                  NUMERIC(16, 6),
    ves_gruz               NUMERIC(10, 2),
    ora_user_edit_row_name VARCHAR(30),
    ora_user_edit_row_date TIMESTAMP(0),
    ora_user_edit_row_lock NUMERIC      default 0 not null,
    vol_gruz               NUMERIC(10, 2),
    id_sch1                VARCHAR(38),
    id_vol                 VARCHAR(38),
    id_sch2                VARCHAR(38),
    id_val                 VARCHAR(38),
    fakt_st                NUMERIC(20, 4),
    kurs                   NUMERIC(12, 4),
    cnt_usl2               NUMERIC(16, 4),
    kpogr2                 NUMERIC(16, 6),
    ves_gruz2              NUMERIC(10, 2),
    vol_gruz2              NUMERIC(10, 2),
    id_vol2                VARCHAR(38),
    fakt_st2               NUMERIC(20, 4),
    kurs2                  NUMERIC(12, 4),
    sum_all                NUMERIC(20, 4),
    sum_all2               NUMERIC(20, 4),
    fakt_usd2              NUMERIC(20, 4),
    fakt_usd               NUMERIC(20, 4),
    cnt_usl1               NUMERIC(16, 4),
    kpogr1                 NUMERIC(16, 6),
    ves_gruz1              NUMERIC(10, 2),
    vol_gruz1              NUMERIC(10, 2),
    id_vol1                VARCHAR(38),
    fakt_st1               NUMERIC(20, 4),
    p_marsh                VARCHAR(100),
    fl_marsh               VARCHAR(150),
    row_creator            VARCHAR(30),
    row_creation_time      TIMESTAMP(0),
    kurs_usd               NUMERIC(12, 4),
    id_val2                VARCHAR(38),
    kurs_usd2              NUMERIC(12, 4),
    id_fl                  VARCHAR(38),
    mest                   NUMERIC(6),
    g32_old                NUMERIC(4),
    id_call                VARCHAR(38),
    id_tk                  VARCHAR(38),
    id_podr                VARCHAR(38),
    id_strn                VARCHAR(38),
    id_doc                 VARCHAR(38),
    id_dog                 VARCHAR(38),
    dt_doc                 TIMESTAMP(0),
    id_svh                 VARCHAR(38),
    id_tzs                 VARCHAR(38),
    id_stt                 VARCHAR(38),
    ng_cox                 INTEGER,
    ngv_cox                NUMERIC(2),
    kngv_cox               NUMERIC(10, 4),
    id_dok                 VARCHAR(38),
    id_upak                VARCHAR(38),
    marker2                VARCHAR(255),
    marker3                VARCHAR(1200),
    id_pack_def            VARCHAR(38),
    ei                     VARCHAR(38),
    storage_cond_id        VARCHAR(38),
    eo_ves_ot              VARCHAR(38),
    eo_ves_do              VARCHAR(38),
    ves_fact               NUMERIC(1),
    alg                    NUMERIC(1),
    tip_coef               VARCHAR(38),
    uei                    VARCHAR(38),
    g32                    VARCHAR(32),
    cnt_uei                NUMERIC(16, 4)
)
    WITH (
        OIDS = FALSE
    );
create table KB_TTN
(
    id                     VARCHAR(38) not null,
    fk_id                  VARCHAR(38),
    id_obsl                VARCHAR(38),
    n_tovar                VARCHAR(255),
    kol_tovar              VARCHAR(40),
    pak_tovar              VARCHAR(255),
    spos_tr                VARCHAR(100),
    st_gruz                NUMERIC(16, 2),
    mest                   NUMERIC(9),
    ves_brutto             NUMERIC(12, 1),
    ttn_n                  VARCHAR(70),
    usl                    VARCHAR(1200),
    ul_otpr                VARCHAR(255),
    adr_otpr               VARCHAR(64),
    fl_otpr                VARCHAR(100),
    ul_pol                 VARCHAR(100),
    adr_pol                VARCHAR(100),
    fl_pol                 VARCHAR(100),
    ora_user_edit_row_name VARCHAR(30),
    ora_user_edit_row_date TIMESTAMP(0),
    ora_user_edit_row_lock NUMERIC     not null,
    row_creator            VARCHAR(30),
    row_creation_time      TIMESTAMP(0),
    id_val                 VARCHAR(38),
    id_ntk                 VARCHAR(38),
    id_tk                  VARCHAR(38),
    id_call                VARCHAR(38),
    id_tir                 VARCHAR(38),
    nedostacha             NUMERIC(16, 3),
    izlishki               NUMERIC(16, 3),
    vozvrat                NUMERIC(16, 3),
    brak                   NUMERIC(16, 3),
    vbd_box                VARCHAR(200),
    srok_godn              TIMESTAMP(0),
    dtd_logic              VARCHAR(7),
    vbd_state_gp           NUMERIC(1)
)
    WITH (
        OIDS = FALSE
    );
create table KB_T_MDET
(
    id_sost VARCHAR(32),
    id_obsl VARCHAR(32),
    f01     VARCHAR(1200),
    f02     VARCHAR(1200),
    f03     VARCHAR(1200),
    f04     VARCHAR(1200),
    f05     VARCHAR(1200),
    f06     VARCHAR(1200),
    f07     VARCHAR(1200),
    f08     VARCHAR(1200),
    f09     VARCHAR(1200),
    f10     VARCHAR(1200),
    f11     VARCHAR(1200),
    f12     VARCHAR(1200),
    f13     VARCHAR(1200),
    f14     VARCHAR(1200),
    f15     VARCHAR(1200),
    f16     VARCHAR(1200),
    f17     VARCHAR(1200),
    f18     VARCHAR(1200),
    f19     VARCHAR(1200),
    f20     VARCHAR(1200),
    f21     VARCHAR(1200)
)
    WITH (
        OIDS = FALSE
    );
create table KB_SPROS
(
    id                     VARCHAR(38)       not null,
    fk_id                  VARCHAR(38),
    n_zakaza               VARCHAR(15),
    dt_zakaz               TIMESTAMP(0),
    id_zak                 VARCHAR(38),
    id_pok                 VARCHAR(38),
    id_dpok                VARCHAR(38),
    fio_knt                VARCHAR(100),
    usl                    VARCHAR(500),
    ora_user_edit_row_name VARCHAR(30),
    ora_user_edit_row_date TIMESTAMP(0),
    ora_user_edit_row_lock NUMERIC default 0 not null,
    id_kat                 VARCHAR(38),
    npost                  VARCHAR(100),
    id_tir                 VARCHAR(38),
    row_creator            VARCHAR(30),
    row_creation_time      TIMESTAMP(0),
    kpost                  NUMERIC(3),
    id_spros               VARCHAR(38),
    kr                     VARCHAR(1),
    n_tir                  VARCHAR(100),
    n_gtd                  VARCHAR(100),
    n_skl                  VARCHAR(50),
    mest                   VARCHAR(10),
    n_gruz                 VARCHAR(50),
    ptd                    NUMERIC(1),
    is_postavka            NUMERIC(1)
)
    WITH (
        OIDS = FALSE
    );
create table KB_ZAK
(
    id                     VARCHAR(38) not null,
    fk_id                  VARCHAR(38),
    id_tip_zak             VARCHAR(38),
    id_tip_zak2            VARCHAR(38),
    inn_zak                VARCHAR(13),
    id_klient              NUMERIC(6),
    id_kopf                VARCHAR(38),
    n_zak                  VARCHAR(256),
    naimen                 VARCHAR(256),
    id_strana              VARCHAR(38),
    p_ind                  NUMERIC(6),
    ur_adr                 VARCHAR(300),
    fio                    VARCHAR(100),
    tlf                    VARCHAR(60),
    fax                    VARCHAR(60),
    email                  VARCHAR(500),
    web                    VARCHAR(60),
    fio_knt                VARCHAR(3000),
    rs                     VARCHAR(20),
    brs                    VARCHAR(70),
    ks                     VARCHAR(20),
    bks                    VARCHAR(70),
    bik                    VARCHAR(10),
    okpo                   NUMERIC(8),
    okonx                  VARCHAR(70),
    id_okonx               VARCHAR(38),
    account                VARCHAR(40),
    baccount               VARCHAR(70),
    swift                  VARCHAR(40),
    licen                  VARCHAR(20),
    dt_licen               TIMESTAMP(0),
    prim                   VARCHAR(500),
    id_ved                 VARCHAR(38),
    ora_user_edit_row_name VARCHAR(30),
    ora_user_edit_row_date TIMESTAMP(0),
    ora_user_edit_row_lock NUMERIC     not null,
    dt_reg                 TIMESTAMP(0),
    fio_rec                VARCHAR(100),
    id_ist                 VARCHAR(38),
    id_fl                  VARCHAR(38),
    dt_end                 TIMESTAMP(0),
    kpp_zak                NUMERIC(9),
    row_creator            VARCHAR(30),
    row_creation_time      TIMESTAMP(0),
    n_eng                  VARCHAR(150),
    adr_eng                VARCHAR(300),
    c_account              VARCHAR(20),
    bacc_int               VARCHAR(70),
    swift_int              VARCHAR(40),
    fio_rod                VARCHAR(100),
    id_usr                 VARCHAR(38),
    tlf_smst               VARCHAR(100),
    rus_sms                NUMERIC(1),
    tir_vod                NUMERIC(1),
    dt_licen_end           TIMESTAMP(0),
    ins_mail               NUMERIC(1),
    kod_no                 VARCHAR(100),
    is_car                 NUMERIC(1),
    is_sup                 NUMERIC(1),
    is_holder              NUMERIC(1),
    is_cust                NUMERIC(1),
    id_wms                 VARCHAR(20),
    id_info                VARCHAR(12),
    prf_wms                VARCHAR(3),
    dn_dost                NUMERIC(2),
    id_no_accept           VARCHAR(38),
    p_in                   NUMERIC(5, 2),
    p_out                  NUMERIC(5, 2),
    p_kol                  INTEGER,
    list_reg               NUMERIC(1),
    am_ord                 NUMERIC(3),
    dov_inf                VARCHAR(4000),
    id_svh                 VARCHAR(38)
)
    WITH (
        OIDS = FALSE
    );
create table KB_TIR
(
    id                     VARCHAR(38) not null,
    fk_id                  VARCHAR(38),
    id_iper                VARCHAR(38),
    id_per                 VARCHAR(38),
    id_dog                 VARCHAR(38),
    id_trans               VARCHAR(38),
    id_tip_tr              VARCHAR(38),
    ob_tr                  VARCHAR(38),
    st_fraht               VARCHAR(22),
    n_avto                 VARCHAR(40),
    n_pric                 VARCHAR(40),
    vodit                  VARCHAR(100),
    n_tir                  VARCHAR(100),
    ves_tir                NUMERIC(7),
    ves_am                 NUMERIC(7),
    cm_n                   VARCHAR(10),
    ora_user_edit_row_name VARCHAR(30),
    ora_user_edit_row_date TIMESTAMP(0),
    ora_user_edit_row_lock NUMERIC     not null,
    ves_pric               NUMERIC(7),
    ves_br_cmr             NUMERIC(7),
    ves_nt_cmr             NUMERIC(7),
    usl                    VARCHAR(2000),
    n_poruch               VARCHAR(20),
    dt_poruch              TIMESTAMP(0),
    marka_ts               VARCHAR(15),
    n_poruch_z             VARCHAR(20),
    dt_poruch_z            TIMESTAMP(0),
    row_creator            VARCHAR(30),
    row_creation_time      TIMESTAMP(0),
    n_cont                 VARCHAR(150),
    n_gtd                  VARCHAR(100),
    n_skl                  VARCHAR(50),
    mest                   VARCHAR(10),
    n_pack                 VARCHAR(15),
    id_klient              NUMERIC(6),
    id_svh                 VARCHAR(38),
    id_osm                 VARCHAR(38),
    id_exp                 VARCHAR(38),
    id_exp_knt             VARCHAR(38),
    id_yam                 VARCHAR(38),
    id_adr                 VARCHAR(38),
    dt_dost                TIMESTAMP(0),
    is_cycle               VARCHAR(38),
    tel_am                 VARCHAR(40),
    ves_ts                 NUMERIC(10, 2)
)
    WITH (
        OIDS = FALSE
    );
create table KB_T_MASTER
(
    id_sost             VARCHAR(32),
    id_obsl             VARCHAR(32),
    id_wms_zak          VARCHAR(32),
    id_wms_pok          VARCHAR(32),
    id_wms_pok_original VARCHAR(32),
    id_wms_per          VARCHAR(32),
    kpost               NUMERIC,
    f01                 VARCHAR(128),
    f02                 VARCHAR(128),
    f03                 VARCHAR(128),
    f04                 VARCHAR(128),
    f05                 VARCHAR(128),
    f06                 VARCHAR(128),
    f07                 VARCHAR(128),
    f08                 VARCHAR(128),
    f09                 VARCHAR(128),
    f10                 VARCHAR(128),
    f11                 VARCHAR(128),
    f12                 VARCHAR(128),
    f13                 VARCHAR(128),
    f14                 VARCHAR(128),
    f15                 VARCHAR(128),
    f16                 VARCHAR(128),
    f17                 VARCHAR(128),
    f18                 VARCHAR(128),
    f19                 VARCHAR(128),
    f20                 VARCHAR(128)
)
    WITH (
        OIDS = FALSE
    );